### ISSUE TITLE
可否再增加一个直接生成pdf的功能?

### ISSUE THREAD

**Issue by 1042970366** [zheyaoa/Resume#1]
大佬,厚着脸皮来给你提意见了~
从以前大佬做的静态页面一直模仿着做,现在我也学了一点node了,现在已经可以完美跑起来这个小项目了,目前正在学习Vue,相信不久后也能模仿大佬这个项目了~跑了下这个项目,发现这个项目要是在加上一个pdf下载功能就好了,用了下chrome自带的网页打印pdf下载,结果发现生成的pdf变得非常丑...大佬还有空在优化一下这个项目吗?

**Comment by zheyaoa** [comment]
啊 不好意思没看到，你现在还需要这个功能吗

**Comment by 1042970366** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        需要哎大佬~能抽空坐下这个功能吗~
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1042970366
                            
                    
                        
                            
                                    1042970366@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年12月18日 11:16，zheyaoa<notifications@github.com> 写道： 


啊 不好意思没看到，你现在还需要这个功能吗



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zheyaoa** [comment]
https://github.com/zheyaoa/Resume/commit/a8fe49d5ff75113f4670ab2f8708163783cf951f
谷歌浏览器打印样式错乱的bug已修复,后期再加 直接生成pdf的功能
